### ISSUE TITLE
Random and silent crashes

### ISSUE THREAD

**Issue by Arnwald** [rsasaki0109/graphslam_ros2#56]
I am testing the nodes with point clouds coming from a Robosense RS16, but the nodes keep crashing randomly without any error message. It just stops and I can't figure why.

Is this behavior normal or am I missing something ?

**Comment by rsasaki0109** [comment]
Does your pc have more than 16gb ram?
Even with 16gb ram, crashes may occur when creating large map point clouds. In that case, more ram is needed.

Also, if you don't mind, could you please provide a rosbag?

**Comment by Arnwald** [comment]
Yes, I have 32Gb and it does not seem to be the origin of the problem (I was monitoring it).

I have to add that I am running the nodes with Galactic.

I tried various parameters but it does not change anything. scanmatcher and graph_based_slam stop listening and publishing, but they don't die and the cpu usage falls to 0.

I will try to do a rosbag next week.

**Comment by Arnwald** [comment]
Do you need a rosbag of the input data or of the output of the slam node ?

**Comment by rsasaki0109** [comment]
I would like it if possible.

**Comment by Arnwald** [comment]
Please find the rosbags under this link,
https://www.swisstransfer.com/d/c3ad9dfc-8470-4826-acf5-d91c13b2266c

The compressed folder contains both the rosbag of the input data (provided by the node from Robosense: https://github.com/RoboSense-LiDAR/rslidar_sdk) and the rosbag of the outputs of lidarslam.

Here are the parameters that I used:

```
scan_matcher:
  ros__parameters:
    global_frame_id: "map"
    robot_frame_id: "base_link"
    registration_method: "NDT"
    ndt_resolution: 2.0
    ndt_num_threads: 0
    gicp_corr_dist_threshold: 5.0
    trans_for_mapupdate: 1.5
    vg_size_for_input: 0.1
    vg_size_for_map: 0.1
    use_min_max_filter: true
    scan_min_range: 5.0
    scan_max_range: 100.0
    scan_period: 0.1
    map_publish_period: 5.0
    num_targeted_cloud: 30
    set_initial_pose: true
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_z: 3.4
    initial_pose_qx: 0.0
    initial_pose_qy: 0.06
    initial_pose_qz: 0.0
    initial_pose_qw: 1.0
    use_imu: false
    use_odom: false
    debug_flag: true

graph_based_slam:
    ros__parameters:
      registration_method: "NDT"
      ndt_resolution: 2.0
      ndt_num_threads: 0
      voxel_leaf_size: 0.2
      loop_detection_period: 1000
      threshold_loop_closure_score: 2.5
      distance_loop_closure: 20.0
      range_of_searching_loop_closure: 20.0
      search_submap_num: 2
      num_adjacent_pose_cnstraints: 5
      use_save_map_in_loop: false
      debug_flag: true
```

I run the nodes under Ubuntu 20.04 with Galactic.
