### ISSUE TITLE
scanmatcher_node-1 process has died

### ISSUE THREAD

**Issue by Tester2009** [rsasaki0109/graphslam_ros2#69]
Hi all.

Currently I'm using ROS2 humble, and using LS Lidar C32. I have recorded a pointcloud in a ros bag and try to play it back in our office.

First I run lidarslam. It run as normal

`ros2 launch lidarslam lidarslam.launch.py`

![Screenshot from 2023-05-30 13-38-09](https://github.com/rsasaki0109/lidarslam_ros2/assets/3969897/27ab9eab-8817-4c30-8687-8f280ba1dac0)

Next, I run RVIZ2 to visualise the path and modified_path. Also, have no issue.

![Screenshot from 2023-05-30 13-38-20](https://github.com/rsasaki0109/lidarslam_ros2/assets/3969897/8c32b592-9775-4a29-853d-685dda96dc3a)

![Screenshot from 2023-05-30 13-39-45](https://github.com/rsasaki0109/lidarslam_ros2/assets/3969897/876a1eb5-85ec-40ee-8afe-056fd646e55e)

After running lidarslam and rviz2, I play the ros2 bag. The way I play the ros bag is as following:

`ros2 bag play file.bag`

![Screenshot from 2023-05-30 13-38-37](https://github.com/rsasaki0109/lidarslam_ros2/assets/3969897/fdfb0794-a935-453c-8680-6372be595771)

After few seconds, the vehicle is moving and now we can see the path. 

![Screenshot from 2023-05-30 13-41-42](https://github.com/rsasaki0109/lidarslam_ros2/assets/3969897/eef6ac50-4809-463d-9344-2343f6d42fea)

Suddenly, there is an error occured in lidarslam. The error is as following:

```
[scanmatcher_node-1] [pcl::VoxelGrid::applyFilter] Leaf size is too small for the input dataset. Integer indices would overflow.
[ERROR] [scanmatcher_node-1]: process has died [pid 121510, exit code -8, cmd '/home/reka/ros2_ws/install/scanmatcher/lib/scanmatcher/scanmatcher_node --ros-args --params-file /home/reka/ros2_ws/install/lidarslam/share/lidarslam/param/lidarslam.yaml -r /input_cloud:=/c32/lslidar_point_cloud'].
```

![Screenshot from 2023-05-30 13-41-53](https://github.com/rsasaki0109/lidarslam_ros2/assets/3969897/13c2a3f9-06d1-405d-b8a6-05aaf0327c9a)

Now, the lidarslam is crash. and the path is not moving anymore. Can I know what the reason behind this and how to fix it?

I tried to fix it by increasing the leaf size in params.yaml, but seems not working.

**Comment by rsasaki0109** [comment]
Can you set scan_matcher.debug_flag to true and check the terminal output just before and just after the node dies? It might contain anomalous values in the input scan for some reason.
You may also want to take a video of the scan with rviz.

scan_matcher.debug_flag
https://github.com/rsasaki0109/lidarslam_ros2/blob/humble/lidarslam/param/lidarslam.yaml#L28

**Comment by Tester2009** [comment]
Thank you @rsasaki0109 for your fast response. I have enabled debug_flag by change it to true value.

Following is the video that I capture when running lidarslam.

[screencast.webm](https://github.com/rsasaki0109/lidarslam_ros2/assets/3969897/a14ebe17-dd1a-459b-8087-6cda8ad9f083)

**Comment by rsasaki0109** [comment]
@Tester2009 I would like you to provide me with the YAML file.

**Comment by Tester2009** [comment]
@rsasaki0109 Here is my YAML file.

```
scan_matcher:
  ros__parameters:
    global_frame_id: "map"
    robot_frame_id: "base_link"
    registration_method: "NDT"
    ndt_resolution: 2.0
    ndt_num_threads: 2
    gicp_corr_dist_threshold: 5.0
    trans_for_mapupdate: 1.5
    vg_size_for_input: 0.5
    vg_size_for_map: 0.1
    use_min_max_filter: true
    scan_min_range: 1.0
    scan_max_range: 200.0
    scan_period: 0.2
    map_publish_period: 15.0
    num_targeted_cloud: 20
    set_initial_pose: true
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_z: 0.0
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: 0.0
    initial_pose_qw: 1.0
    use_imu: false
    use_odom: false
    debug_flag: true

graph_based_slam:
    ros__parameters:
      registration_method: "NDT"
      ndt_resolution: 1.0
      ndt_num_threads: 2
      voxel_leaf_size: 0.1
      loop_detection_period: 3000
      threshold_loop_closure_score: 0.7
      distance_loop_closure: 100.0
      range_of_searching_loop_closure: 20.0
      search_submap_num: 2
      num_adjacent_pose_cnstraints: 5
      use_save_map_in_loop: true
      debug_flag: true
```
