### ISSUE TITLE
Frame Changes

### ISSUE THREAD

**Issue by theinge9** [rsasaki0109/graphslam_ros2#92]
I am trying this repository with my 3D LiDAR and it perfectly works in simple environment which has no many direction changes.
But when i try in the environment with a lot of corner, my LiDAR frame changes a lot and cannot find loop closures. How should i fix this in which config parameters?Thanks for your great work. 
I am using only 3D LiDAR without IMU.

![f1](https://github.com/rsasaki0109/lidarslam_ros2/assets/138423325/9bc4cafe-4a69-4558-b329-26f69b95525b)

**Comment by rsasaki0109** [comment]
It seems like the scan matching is failing around the bottom right of the image.
Could you provide the parameter YAML file you are using?

**Comment by theinge9** [comment]
I am using the following yaml file which is not different with the origin of lidarslam.
```
scan_matcher:
  ros__parameters:
    global_frame_id: "map"
    robot_frame_id: "base_link"
    registration_method: "NDT"
    ndt_resolution: 2.0
    ndt_num_threads: 2
    gicp_corr_dist_threshold: 5.0
    trans_for_mapupdate: 1.5
    vg_size_for_input: 0.5
    vg_size_for_map: 0.1
    use_min_max_filter: true
    scan_min_range: 1.0
    scan_max_range: 200.0
    scan_period: 0.2
    map_publish_period: 15.0
    num_targeted_cloud: 20
    set_initial_pose: true
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_z: 0.0
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: 0.0
    initial_pose_qw: 1.0
    use_imu: false
    use_odom: false
    debug_flag: false

graph_based_slam:
    ros__parameters:
      registration_method: "NDT"
      ndt_resolution: 1.0
      ndt_num_threads: 2
      voxel_leaf_size: 0.1
      loop_detection_period: 3000
      threshold_loop_closure_score: 0.7
      distance_loop_closure: 100.0
      range_of_searching_loop_closure: 20.0
      search_submap_num: 2
      num_adjacent_pose_cnstraints: 5
      use_save_map_in_loop: true
      debug_flag: true
```
